### ISSUE TITLE
Can't verify my Aadhaar QR

### ISSUE THREAD

**Issue by Karan9034** [anon-aadhaar/devcon7#3]
I'm getting an error everytime I upload the QR to verify for Devcon. 

![image](https://github.com/user-attachments/assets/8a0d6408-11d3-446d-a0f0-945b6a7423d9)

**Comment by Karan9034** [comment]
cc: @saleel @Meyanis95

**Comment by Meyanis95** [comment]
Hey @Karan9034 

Did you get your QR Code on the mAadhaar app?

**Comment by Karan9034** [comment]
Yes

**Comment by Meyanis95** [comment]
Have already used a previous version of Anon Aadhaar on this Browser? 
Could you please try to delete all your cache and try again?

**Comment by Karan9034** [comment]
No never used Anon Aadhaar before.
Trying this on Incognito, so cache is being cleared automatically.

**Comment by Karan9034** [comment]
The message goes upto "Generating Proof", then changes to "Oops, something went wrong".
Console shows out of bounds error.

**Comment by Meyanis95** [comment]
Are these files present in your indexedDB? 

<img width="499" alt="image" src="https://github.com/user-attachments/assets/97d2c0ac-9a62-42ed-9594-92d57baf3d97">

**Comment by lokesh-katari** [comment]
@Meyanis95  same for me also , cannot verify my aadhar
![image](https://github.com/user-attachments/assets/f8261d62-12ed-4155-9623-dd8357dc5e23)

**Comment by Karan9034** [comment]
Hey, I figured out what's the issue. For some reason the "Generating Proof" part doesn't work in incognito mode. Using it normally should work fine. Also discount coupons for devcon through anon aadhaar were over when I last checked, so there's no point doing it now.

**Comment by lokesh-katari** [comment]
@Karan9034  ,thanks for letting me know about the devcon tickets :)

**Comment by Meyanis95** [comment]
Hey guys
We've added some extra vouchers if you still want to redeem one, please do it ASAP
